import type { PricingProduct } from "@/lib/pricing"

const IMG = "https://cardiopro.fr/images"

/** Conversion grille FR → CHF Suisse (+100 sur les montants EUR). */
export function eurToChf(eur: number): number {
  return eur + 100
}

function chfLabel(eur: number): string {
  return `CHF ${eurToChf(eur).toLocaleString("fr-CH").replace(/\u00a0/g, " ")}.–`
}

type ProductSeed = {
  id: string
  model: string
  brand: string
  type: "DAE" | "DSA"
  typeLabelFr: string
  typeLabelDe: string
  taglineFr: string
  taglineDe: string
  priceEur: number
  cost4yEur: number
  warranty: number
  ip: string
  weight: string
  featuresFr: string[]
  featuresDe: string[]
  image: string
  electrodesEur?: number | "padpak" | "incl"
  batteryEur?: number | "padpak" | "incl" | "zero"
}

const seeds: ProductSeed[] = [
  {
    id: "iaed-s1",
    model: "iAED-S1",
    brand: "Noah Medical",
    type: "DAE",
    typeLabelFr: "DAE automatique",
    typeLabelDe: "Vollautomatischer AED",
    taglineFr: "Le moins cher",
    taglineDe: "Der günstigste",
    priceEur: 990,
    cost4yEur: 1080,
    warranty: 4,
    ip: "IP55",
    weight: "1,8 kg",
    featuresFr: ["Détection pacemaker", "Temps de charge < 7 sec", "Électrodes universelles adulte/enfant"],
    featuresDe: ["Schrittmacher-Erkennung", "Ladezeit < 7 Sek.", "Universalelektroden Erwachsene/Kind"],
    image: `${IMG}/defibrillateurs/CARDIO_REX_IAD.webp`,
    electrodesEur: 90,
    batteryEur: 150,
  },
  {
    id: "heartsine-360p",
    model: "HeartSine 360P",
    brand: "HeartSine",
    type: "DAE",
    typeLabelFr: "DAE automatique",
    typeLabelDe: "Vollautomatischer AED",
    taglineFr: "Garantie 10 ans",
    taglineDe: "10 Jahre Garantie",
    priceEur: 990,
    cost4yEur: 1170,
    warranty: 10,
    ip: "IP56",
    weight: "1,1 kg",
    featuresFr: ["Défibrillation auto sans bouton", "PadPak électrodes + batterie intégré", "Idéal pour personnel non formé"],
    featuresDe: ["Automatische Defibrillation ohne Taste", "PadPak Elektroden + Batterie integriert", "Ideal für ungeschultes Personal"],
    image: `${IMG}/defibrillateur-automatique-Heartsine-360P.webp`,
    electrodesEur: "padpak",
    batteryEur: "incl",
  },
  {
    id: "heartsine-350p",
    model: "HeartSine 350P",
    brand: "HeartSine",
    type: "DSA",
    typeLabelFr: "DSA semi-automatique",
    typeLabelDe: "Halbautomatischer AED",
    taglineFr: "Le plus léger",
    taglineDe: "Der leichteste",
    priceEur: 1090,
    cost4yEur: 1270,
    warranty: 8,
    ip: "IP56",
    weight: "1,1 kg",
    featuresFr: ["PadPak électrodes + batterie intégré", "Guidage vocal étape par étape", "Coût de possession le plus bas"],
    featuresDe: ["PadPak Elektroden + Batterie integriert", "Schritt-für-Schritt-Sprachführung", "Niedrigste Gesamtbetriebskosten"],
    image: `${IMG}/defibrillateur-semi-automatique-Heartsine-350P.webp`,
    electrodesEur: "padpak",
    batteryEur: "incl",
  },
  {
    id: "heartsine-500p",
    model: "HeartSine 500P",
    brand: "HeartSine",
    type: "DAE",
    typeLabelFr: "DAE avec CPR Advisor",
    typeLabelDe: "AED mit CPR Advisor",
    taglineFr: "Recommandé ERP",
    taglineDe: "Empfohlen für ERP",
    priceEur: 1490,
    cost4yEur: 1670,
    warranty: 8,
    ip: "IP56",
    weight: "1,1 kg",
    featuresFr: ["Feedback massage cardiaque en temps réel", "Mesure l'efficacité des compressions", "Recommandé entreprises & lieux publics"],
    featuresDe: ["Herzdruckmassage-Feedback in Echtzeit", "Misst die Effektivität der Kompressionen", "Empfohlen für Unternehmen & Publikum"],
    image: `${IMG}/defibrillateurs/500P.webp`,
    electrodesEur: "padpak",
    batteryEur: "incl",
  },
  {
    id: "mediana-a16",
    model: "Mediana A16",
    brand: "Mediana",
    type: "DAE",
    typeLabelFr: "DAE/DSA commutable",
    typeLabelDe: "Umschaltbar AED/halbautomatisch",
    taglineFr: "Meilleur rapport Q/P",
    taglineDe: "Bestes Preis-Leistungs-Verhältnis",
    priceEur: 1290,
    cost4yEur: 1180,
    warranty: 10,
    ip: "IP55",
    weight: "2,0 kg",
    featuresFr: ["Mode DAE ou DSA au choix", "Écran LCD couleur", "Excellent rapport qualité/prix"],
    featuresDe: ["AED- oder halbautomatischer Modus wählbar", "LCD-Farbdisplay", "Hervorragendes Preis-Leistungs-Verhältnis"],
    image: `${IMG}/defibrillateurs/MEDIANA_A_16.webp`,
    electrodesEur: 85,
    batteryEur: 170,
  },
  {
    id: "fred-pa-1",
    model: "FRED PA-1",
    brand: "Schiller",
    type: "DAE",
    typeLabelFr: "DAE automatique",
    typeLabelDe: "Vollautomatischer AED",
    taglineFr: "Batterie 6 ans",
    taglineDe: "Batterie 6 Jahre",
    priceEur: 1290,
    cost4yEur: 1230,
    warranty: 10,
    ip: "IP55",
    weight: "—",
    featuresFr: ["Batterie 6 ans (sans remplacement)", "Robuste et fiable", "Électrodes longue durée (30 mois)"],
    featuresDe: ["Batterie 6 Jahre (kein Austausch)", "Robust und zuverlässig", "Langlebige Elektroden (30 Monate)"],
    image: `${IMG}/defibrillateurs/FRED_P1.webp`,
    electrodesEur: 130,
    batteryEur: "zero",
  },
  {
    id: "reanibex-100",
    model: "Reanibex 100",
    brand: "Bexen",
    type: "DAE",
    typeLabelFr: "DAE connecté",
    typeLabelDe: "Vernetzter AED",
    taglineFr: "WiFi connecté",
    taglineDe: "WiFi-vernetzt",
    priceEur: 1190,
    cost4yEur: 1207,
    warranty: 7,
    ip: "IP55",
    weight: "1,95 kg",
    featuresFr: ["Mise en marche auto à l'ouverture", "Design compact", "Connecté WiFi / Sigfox"],
    featuresDe: ["Automatischer Start beim Öffnen", "Kompaktes Design", "WiFi / Sigfox vernetzt"],
    image: `${IMG}/defibrillateurs/REANIBEX.webp`,
    electrodesEur: 92,
    batteryEur: 100,
  },
  {
    id: "zoll-aed-plus",
    model: "ZOLL AED Plus",
    brand: "ZOLL",
    type: "DSA",
    typeLabelFr: "DSA avec Real CPR Help",
    typeLabelDe: "Halbautomatisch mit Real CPR Help",
    taglineFr: "Aide massage intégrée",
    taglineDe: "Integrierte Reanimationshilfe",
    priceEur: 1590,
    cost4yEur: 1590,
    warranty: 7,
    ip: "IP55",
    weight: "2,3 kg",
    featuresFr: ["Capteur de massage cardiaque intégré", "Couvercle = aide au massage", "Robuste, usage intensif"],
    featuresDe: ["Integrierter Herzdruckmassage-Sensor", "Deckel = Reanimationshilfe", "Robust, intensive Nutzung"],
    image: `${IMG}/defibrillateurs/AED_PLUS.webp`,
    electrodesEur: 210,
    batteryEur: 170,
  },
  {
    id: "zoll-aed-3",
    model: "ZOLL AED 3",
    brand: "ZOLL",
    type: "DAE",
    typeLabelFr: "DAE écran LCD",
    typeLabelDe: "AED mit LCD-Display",
    taglineFr: "Premium",
    taglineDe: "Premium",
    priceEur: 2095,
    cost4yEur: 2305,
    warranty: 8,
    ip: "IP55",
    weight: "2,5 kg",
    featuresFr: ["Écran LCD + vidéo d'aide", "Real CPR Help (feedback massage)", "WiFi connecté pour la maintenance"],
    featuresDe: ["LCD-Display + Hilfevideo", "Real CPR Help (Massage-Feedback)", "WiFi-vernetzt für die Wartung"],
    image: `${IMG}/defibrillateurs/ZOLL_3.webp`,
    electrodesEur: 210,
    batteryEur: 170,
  },
  {
    id: "philips-frx",
    model: "Philips HeartStart FRx",
    brand: "Philips",
    type: "DSA",
    typeLabelFr: "DSA semi-automatique",
    typeLabelDe: "Halbautomatischer AED",
    taglineFr: "Le plus robuste",
    taglineDe: "Am robustesten",
    priceEur: 1390,
    cost4yEur: 1680,
    warranty: 8,
    ip: "IP55",
    weight: "1,6 kg",
    featuresFr: ["+250 000 appareils dans le monde", "Quick Shock < 8 sec, norme militaire", "Clé pédiatrique optionnelle"],
    featuresDe: ["+250 000 Geräte weltweit", "Quick Shock < 8 Sek., Militärnorm", "Optionale Kinderschlüssel"],
    image: `${IMG}/defibrillateurs/PHILIPS_FRX.webp`,
    electrodesEur: 120,
    batteryEur: 170,
  },
  {
    id: "mindray-c2",
    model: "Mindray BeneHeart C2",
    brand: "Mindray",
    type: "DAE",
    typeLabelFr: "DAE/DSA commutable",
    typeLabelDe: "Umschaltbar AED/halbautomatisch",
    taglineFr: "Écran vidéo 7\"",
    taglineDe: "7\" Video-Display",
    priceEur: 1410,
    cost4yEur: 1530,
    warranty: 8,
    ip: "IP55",
    weight: "2,4 kg",
    featuresFr: ["Écran vidéo 7\" couleur + animations", "ResQNavi™ adapte le guidage", "Électrodes universelles adulte/enfant"],
    featuresDe: ["7\" Farbvideo-Display + Animationen", "ResQNavi™ passt die Führung an", "Universalelektroden Erwachsene/Kind"],
    image: `${IMG}/defibrillateurs/MINDRAY_C2.webp`,
    electrodesEur: 120,
    batteryEur: 160,
  },
  {
    id: "powerheart-g5",
    model: "Powerheart G5",
    brand: "Cardiac Science",
    type: "DAE",
    typeLabelFr: "DAE automatique",
    typeLabelDe: "Vollautomatischer AED",
    taglineFr: "Capteur RCP intégré",
    taglineDe: "Integrierter CPR-Sensor",
    priceEur: 1490,
    cost4yEur: 1780,
    warranty: 8,
    ip: "IP55",
    weight: "2,5 kg",
    featuresFr: ["Énergie variable 95–354J", "Capteur RCP dans les électrodes", "Norme militaire MIL-STD-810G"],
    featuresDe: ["Variable Energie 95–354J", "CPR-Sensor in den Elektroden", "Militärnorm MIL-STD-810G"],
    image: `${IMG}/defibrillateurs/POWERHEART_G5.webp`,
    electrodesEur: 130,
    batteryEur: 160,
  },
  {
    id: "primedic-mypad-lcd-rcp",
    model: "Primedic MyPad LCD+RCP",
    brand: "Primedic",
    type: "DAE",
    typeLabelFr: "DAE automatique",
    typeLabelDe: "Vollautomatischer AED",
    taglineFr: "Top configuration",
    taglineDe: "Top-Konfiguration",
    priceEur: 1500,
    cost4yEur: 1770,
    warranty: 5,
    ip: "IP66",
    weight: "1,1 kg",
    featuresFr: ["Écran LCD couleur 4,3\"", "Capteur RCP feedback massage", "Mode enfant intégré"],
    featuresDe: ["4,3\" LCD-Farbdisplay", "CPR-Sensor mit Massage-Feedback", "Integrierter Kindermodus"],
    image: `${IMG}/defibrillateurs/PRIMEDIC_MYPAD_LCD_RCP.webp`,
    electrodesEur: 130,
    batteryEur: 140,
  },
  {
    id: "primedic-mypad-lcd",
    model: "Primedic MyPad LCD",
    brand: "Primedic",
    type: "DAE",
    typeLabelFr: "DAE automatique",
    typeLabelDe: "Vollautomatischer AED",
    taglineFr: "Écran couleur",
    taglineDe: "Farbbildschirm",
    priceEur: 1400,
    cost4yEur: 1670,
    warranty: 5,
    ip: "IP66",
    weight: "1,1 kg",
    featuresFr: ["Écran LCD couleur 4,3\"", "Mode enfant intégré", "Compact 15×15 cm"],
    featuresDe: ["4,3\" LCD-Farbdisplay", "Integrierter Kindermodus", "Kompakt 15×15 cm"],
    image: `${IMG}/defibrillateurs/PRIMEDIC_MYPAD_LCD.webp`,
    electrodesEur: 130,
    batteryEur: 140,
  },
  {
    id: "primedic-mypad-rcp",
    model: "Primedic MyPad RCP",
    brand: "Primedic",
    type: "DAE",
    typeLabelFr: "DAE automatique",
    typeLabelDe: "Vollautomatischer AED",
    taglineFr: "Avec capteur RCP",
    taglineDe: "Mit CPR-Sensor",
    priceEur: 1300,
    cost4yEur: 1570,
    warranty: 5,
    ip: "IP66",
    weight: "1,1 kg",
    featuresFr: ["Capteur RCP feedback massage", "Mode enfant intégré", "Fabriqué en Allemagne"],
    featuresDe: ["CPR-Sensor mit Massage-Feedback", "Integrierter Kindermodus", "Hergestellt in Deutschland"],
    image: `${IMG}/defibrillateurs/PRIMEDIC_MYPAD_RCP.webp`,
    electrodesEur: 130,
    batteryEur: 140,
  },
  {
    id: "primedic-mypad",
    model: "Primedic MyPad",
    brand: "Primedic",
    type: "DAE",
    typeLabelFr: "DAE automatique",
    typeLabelDe: "Vollautomatischer AED",
    taglineFr: "Entrée gamme",
    taglineDe: "Einstiegsmodell",
    priceEur: 1300,
    cost4yEur: 1570,
    warranty: 5,
    ip: "IP66",
    weight: "1,1 kg",
    featuresFr: ["Ultra-compact 15×15 cm · 1,1 kg", "Mode enfant intégré", "IP66"],
    featuresDe: ["Ultrakompakt 15×15 cm · 1,1 kg", "Integrierter Kindermodus", "IP66"],
    image: `${IMG}/defibrillateurs/PRIMEDIC_MYPAD.webp`,
    electrodesEur: 130,
    batteryEur: 140,
  },
  {
    id: "smarty-saver",
    model: "Smarty Saver Automatique",
    brand: "Progetti",
    type: "DAE",
    typeLabelFr: "DAE automatique",
    typeLabelDe: "Vollautomatischer AED",
    taglineFr: "Automatique pas cher",
    taglineDe: "Günstiger Automatik-AED",
    priceEur: 1200,
    cost4yEur: 1410,
    warranty: 5,
    ip: "IP54",
    weight: "—",
    featuresFr: ["Mise en marche auto à l'ouverture", "Compatible adulte/enfant", "Trousse de secours incluse"],
    featuresDe: ["Automatischer Start beim Öffnen", "Erwachsene/Kind kompatibel", "Erste-Hilfe-Set inklusive"],
    image: `${IMG}/defibrillateurs/SMARTY_SAVER.webp`,
    electrodesEur: 100,
    batteryEur: 110,
  },
  {
    id: "iaed-s1-pro-4g",
    model: "iAED-S1 Pro 4G",
    brand: "Noah Medical",
    type: "DAE",
    typeLabelFr: "DAE avec télésurveillance",
    typeLabelDe: "AED mit Telematik",
    taglineFr: "4G connecté",
    taglineDe: "4G-vernetzt",
    priceEur: 1090,
    cost4yEur: 1180,
    warranty: 4,
    ip: "IP55",
    weight: "1,8 kg",
    featuresFr: ["Contrôleur 4G intégré", "Télésurveillance batterie/électrodes", "Alerte ouverture boîtier"],
    featuresDe: ["Integrierter 4G-Controller", "Fernüberwachung Batterie/Elektroden", "Alarm bei Gehäuseöffnung"],
    image: `${IMG}/defibrillateurs/IAED_S1_COM.webp`,
    electrodesEur: 90,
    batteryEur: 150,
  },
  {
    id: "defibtech-lifeline-auto",
    model: "Defibtech Lifeline Automatique",
    brand: "Defibtech",
    type: "DAE",
    typeLabelFr: "DAE automatique",
    typeLabelDe: "Vollautomatischer AED",
    taglineFr: "Garantie 8 ans",
    taglineDe: "8 Jahre Garantie",
    priceEur: 2875,
    cost4yEur: 3075,
    warranty: 8,
    ip: "IP54",
    weight: "—",
    featuresFr: ["Choc délivré automatiquement", "Batterie 5 ans (option 7)", "Fabrication USA robuste"],
    featuresDe: ["Schock wird automatisch abgegeben", "Batterie 5 Jahre (Option 7)", "Robuste US-Fertigung"],
    image: `${IMG}/defibrillateurs/DEFIBTECH_LIFELINE_AUTO.webp`,
    electrodesEur: 100,
    batteryEur: 100,
  },
  {
    id: "defibtech-lifeline-semi",
    model: "Defibtech Lifeline Semi-Automatique",
    brand: "Defibtech",
    type: "DSA",
    typeLabelFr: "DSA semi-automatique",
    typeLabelDe: "Halbautomatischer AED",
    taglineFr: "Garantie 8 ans",
    taglineDe: "8 Jahre Garantie",
    priceEur: 2750,
    cost4yEur: 2950,
    warranty: 8,
    ip: "IP54",
    weight: "—",
    featuresFr: ["Bouton choc utilisateur", "Batterie 5 ans (option 7)", "Fabrication USA robuste"],
    featuresDe: ["Schocktaste für den Anwender", "Batterie 5 Jahre (Option 7)", "Robuste US-Fertigung"],
    image: `${IMG}/defibrillateurs/DEFIBTECH_LIFELINE_SEMI.webp`,
    electrodesEur: 100,
    batteryEur: 100,
  },
  {
    id: "defibtech-view",
    model: "Defibtech View",
    brand: "Defibtech",
    type: "DSA",
    typeLabelFr: "DSA avec guide vidéo",
    typeLabelDe: "Halbautomatisch mit Video",
    taglineFr: "Écran vidéo couleur",
    taglineDe: "Farbiges Video-Display",
    priceEur: 2880,
    cost4yEur: 3080,
    warranty: 8,
    ip: "IP54",
    weight: "—",
    featuresFr: ["Écran couleur LCD vidéo d'aide", "Guidage visuel pour non formés", "Mise à jour via carte SD"],
    featuresDe: ["Farbiges LCD-Video mit Anleitung", "Visuelle Führung für Laien", "Update per SD-Karte"],
    image: `${IMG}/defibrillateurs/DEFIBTECH_VIEW.webp`,
    electrodesEur: 100,
    batteryEur: 100,
  },
  {
    id: "mindray-c1a-auto",
    model: "Mindray BeneHeart C1A Automatique",
    brand: "Mindray",
    type: "DAE",
    typeLabelFr: "DAE automatique",
    typeLabelDe: "Vollautomatischer AED",
    taglineFr: "Compact Mindray",
    taglineDe: "Kompakter Mindray",
    priceEur: 1500,
    cost4yEur: 1620,
    warranty: 8,
    ip: "IP55",
    weight: "2,2 kg",
    featuresFr: ["Choc délivré automatiquement", "Batterie 5 ans longue durée", "Électrodes universelles adulte/enfant"],
    featuresDe: ["Schock wird automatisch abgegeben", "Langlebige 5-Jahres-Batterie", "Universalelektroden Erwachsene/Kind"],
    image: `${IMG}/defibrillateurs/MINDRAY_C1A_AUTO.webp`,
    electrodesEur: 120,
    batteryEur: 160,
  },
  {
    id: "mindray-c1a-semi",
    model: "Mindray BeneHeart C1A Semi-Automatique",
    brand: "Mindray",
    type: "DSA",
    typeLabelFr: "DSA semi-automatique",
    typeLabelDe: "Halbautomatischer AED",
    taglineFr: "Compact Mindray",
    taglineDe: "Kompakter Mindray",
    priceEur: 1500,
    cost4yEur: 1620,
    warranty: 8,
    ip: "IP55",
    weight: "2,2 kg",
    featuresFr: ["Bouton choc utilisateur", "Batterie 5 ans longue durée", "Électrodes universelles adulte/enfant"],
    featuresDe: ["Schocktaste für den Anwender", "Langlebige 5-Jahres-Batterie", "Universalelektroden Erwachsene/Kind"],
    image: `${IMG}/defibrillateurs/MINDRAY_C1A_SEMI.webp`,
    electrodesEur: 120,
    batteryEur: 160,
  },
  {
    id: "mindray-c2a-auto",
    model: "Mindray BeneHeart C2A Automatique",
    brand: "Mindray",
    type: "DAE",
    typeLabelFr: "DAE connecté",
    typeLabelDe: "Vernetzter AED",
    taglineFr: "Connecté 4G/WiFi",
    taglineDe: "4G/WiFi-vernetzt",
    priceEur: 2100,
    cost4yEur: 2220,
    warranty: 8,
    ip: "IP55",
    weight: "2,4 kg",
    featuresFr: ["Connectivité 4G/WiFi intégrée", "Écran couleur ResQNavi™", "Choc délivré automatiquement"],
    featuresDe: ["Integrierte 4G/WiFi-Konnektivität", "Farbdisplay ResQNavi™", "Schock wird automatisch abgegeben"],
    image: `${IMG}/defibrillateurs/MINDRAY_C2A_AUTO.webp`,
    electrodesEur: 120,
    batteryEur: 160,
  },
  {
    id: "mindray-c2a-semi",
    model: "Mindray BeneHeart C2A Semi-Automatique",
    brand: "Mindray",
    type: "DSA",
    typeLabelFr: "DSA connecté",
    typeLabelDe: "Vernetzter halbautomatischer AED",
    taglineFr: "Connecté 4G/WiFi",
    taglineDe: "4G/WiFi-vernetzt",
    priceEur: 2100,
    cost4yEur: 2220,
    warranty: 8,
    ip: "IP55",
    weight: "2,4 kg",
    featuresFr: ["Connectivité 4G/WiFi intégrée", "Écran couleur ResQNavi™", "Bouton choc utilisateur"],
    featuresDe: ["Integrierte 4G/WiFi-Konnektivität", "Farbdisplay ResQNavi™", "Schocktaste für den Anwender"],
    image: `${IMG}/defibrillateurs/MINDRAY_C2A_SEMI.webp`,
    electrodesEur: 120,
    batteryEur: 160,
  },
  {
    id: "philips-hs1",
    model: "Philips HeartStart HS1",
    brand: "Philips",
    type: "DSA",
    typeLabelFr: "DSA grand public",
    typeLabelDe: "Halbautomatisch für Laien",
    taglineFr: "Best-seller mondial",
    taglineDe: "Weltweiter Bestseller",
    priceEur: 1550,
    cost4yEur: 1850,
    warranty: 8,
    ip: "IP21",
    weight: "1,5 kg",
    featuresFr: ["Conçu pour grand public sans formation", "SMART Pads adulte analyse intelligente", "Auto-test quotidien"],
    featuresDe: ["Für Laien ohne Schulung konzipiert", "SMART Pads Erwachsene mit intelligenter Analyse", "Täglicher Selbsttest"],
    image: `${IMG}/defibrillateurs/PHILIPS_HS1.webp`,
    electrodesEur: 150,
    batteryEur: 150,
  },
  {
    id: "lifepak-cr2-usb-auto",
    model: "LIFEPAK CR2 USB Automatique",
    brand: "Stryker",
    type: "DAE",
    typeLabelFr: "DAE professionnel",
    typeLabelDe: "Professioneller AED",
    taglineFr: "Référence pro",
    taglineDe: "Profi-Referenz",
    priceEur: 2498,
    cost4yEur: 2800,
    warranty: 8,
    ip: "IP55",
    weight: "2 kg",
    featuresFr: ["Compressions sans interruption cprINSIGHT™", "Choc délivré automatiquement", "Export données USB"],
    featuresDe: ["Kompressionen ohne Unterbrechung cprINSIGHT™", "Schock wird automatisch abgegeben", "USB-Datenexport"],
    image: `${IMG}/defibrillateurs/LIFEPAK_CR2_USB_AUTO.webp`,
    electrodesEur: 152,
    batteryEur: 150,
  },
  {
    id: "lifepak-cr2-usb-semi",
    model: "LIFEPAK CR2 USB Semi-Automatique",
    brand: "Stryker",
    type: "DSA",
    typeLabelFr: "DSA professionnel",
    typeLabelDe: "Professioneller halbautomatischer AED",
    taglineFr: "Référence pro",
    taglineDe: "Profi-Referenz",
    priceEur: 5390,
    cost4yEur: 5690,
    warranty: 8,
    ip: "IP55",
    weight: "2 kg",
    featuresFr: ["Compressions sans interruption cprINSIGHT™", "Bouton choc utilisateur", "Export données USB"],
    featuresDe: ["Kompressionen ohne Unterbrechung cprINSIGHT™", "Schocktaste für den Anwender", "USB-Datenexport"],
    image: `${IMG}/defibrillateurs/LIFEPAK_CR2_USB_SEMI.webp`,
    electrodesEur: 152,
    batteryEur: 150,
  },
  {
    id: "lifepak-cr2-wifi-auto",
    model: "LIFEPAK CR2 WiFi Automatique",
    brand: "Stryker",
    type: "DAE",
    typeLabelFr: "DAE connecté",
    typeLabelDe: "Vernetzter AED",
    taglineFr: "WiFi connecté",
    taglineDe: "WiFi-vernetzt",
    priceEur: 3058,
    cost4yEur: 3360,
    warranty: 8,
    ip: "IP55",
    weight: "2 kg",
    featuresFr: ["Surveillance distance LIFELINKcentral™", "Choc délivré automatiquement", "Compressions cprINSIGHT™"],
    featuresDe: ["Fernüberwachung LIFELINKcentral™", "Schock wird automatisch abgegeben", "Kompressionen cprINSIGHT™"],
    image: `${IMG}/defibrillateurs/LIFEPAK_CR2_WIFI_AUTO.webp`,
    electrodesEur: 152,
    batteryEur: 150,
  },
  {
    id: "lifepak-cr2-wifi-semi",
    model: "LIFEPAK CR2 WiFi Semi-Automatique",
    brand: "Stryker",
    type: "DSA",
    typeLabelFr: "DSA connecté",
    typeLabelDe: "Vernetzter halbautomatischer AED",
    taglineFr: "WiFi connecté",
    taglineDe: "WiFi-vernetzt",
    priceEur: 2858,
    cost4yEur: 3160,
    warranty: 8,
    ip: "IP55",
    weight: "2 kg",
    featuresFr: ["Surveillance distance LIFELINKcentral™", "Bouton choc utilisateur", "Compressions cprINSIGHT™"],
    featuresDe: ["Fernüberwachung LIFELINKcentral™", "Schocktaste für den Anwender", "Kompressionen cprINSIGHT™"],
    image: `${IMG}/defibrillateurs/LIFEPAK_CR2_WIFI_SEMI.webp`,
    electrodesEur: 152,
    batteryEur: 150,
  },
  {
    id: "zoll-aed-3-semi",
    model: "ZOLL AED 3 Semi-Automatique",
    brand: "ZOLL",
    type: "DSA",
    typeLabelFr: "DSA écran LCD",
    typeLabelDe: "Halbautomatisch mit LCD",
    taglineFr: "Premium",
    taglineDe: "Premium",
    priceEur: 2500,
    cost4yEur: 2710,
    warranty: 8,
    ip: "IP55",
    weight: "2,5 kg",
    featuresFr: ["Écran LCD + vidéo d'aide", "Real CPR Help feedback massage", "WiFi connecté maintenance"],
    featuresDe: ["LCD-Display + Hilfevideo", "Real CPR Help Massage-Feedback", "WiFi-vernetzt für Wartung"],
    image: `${IMG}/defibrillateurs/ZOLL_AED_3_SEMI.webp`,
    electrodesEur: 210,
    batteryEur: 170,
  },
]

function labelElectrodes(v: ProductSeed["electrodesEur"], lang: "fr" | "de"): string {
  if (v === "padpak") return lang === "fr" ? "CHF 190.– (PadPak)" : "CHF 190.– (PadPak)"
  if (v === "incl") return lang === "fr" ? "inclus" : "inkl."
  if (typeof v === "number") return chfLabel(v)
  return "—"
}

function labelBattery(v: ProductSeed["batteryEur"], lang: "fr" | "de"): string {
  if (v === "padpak") return lang === "fr" ? "incl. PadPak" : "im PadPak"
  if (v === "incl") return lang === "fr" ? "inclus" : "inkl."
  if (v === "zero") return lang === "fr" ? "CHF 0.–*" : "CHF 0.–*"
  if (typeof v === "number") return chfLabel(v)
  return "—"
}

function buildProducts(lang: "fr" | "de"): PricingProduct[] {
  return seeds.map((s) => ({
    id: s.id,
    model: s.model,
    brand: s.brand,
    type: s.type,
    typeLabel: lang === "fr" ? s.typeLabelFr : s.typeLabelDe,
    tagline: lang === "fr" ? s.taglineFr : s.taglineDe,
    price: eurToChf(s.priceEur),
    cost4y: eurToChf(s.cost4yEur),
    warranty: s.warranty,
    ip: s.ip,
    weight: s.weight,
    features: lang === "fr" ? s.featuresFr : s.featuresDe,
    image: s.image,
    electrodesLabel: labelElectrodes(s.electrodesEur, lang),
    batteryLabel: labelBattery(s.batteryEur, lang),
  }))
}

export const productsFr: PricingProduct[] = buildProducts("fr")
export const productsDe: PricingProduct[] = buildProducts("de")

export const pricingRangeChf = {
  minPrice: eurToChf(990),
  maxPrice: eurToChf(5390),
  minCost4y: eurToChf(1080),
  maxCost4y: eurToChf(5690),
}
